export const CommonErrors = {
  AUTHENTICATION_ERROR: `Authentication Error`,
  AUTHORIZATION_ERROR: `Authorization Error`,
  INPUT_ERROR: `Input Error`,
  ARGUMENT_ERROR: `Argument Error`,
  BUSINESS_ERROR: `Business Error`,
  CONFIG_ERROR: `Config Error`,
  DATABASE_ERROR: `DB Error`,
  FATAL_ERROR: `Fatal Error`,
  OBJECT_CREATION_ERROR: `Object Creation Error`,
  RESOURCE_NOT_FOUND_ERROR: `Resource Not Found Error`,
  RESOURCE_DUPLICATION_ERROR: `Resource Duplication Error`,
  REMOTE_STORAGE_ERROR: `Remote Storage Error`,
  REQUEST_VALIDATION_ERROR: 'Request Validation Error',
};
